name: Test code on checkin

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Display the version of go that we have installed
        run: go version

      - name: Examine Go source code and report suspicious constructs
        run: go vet

      #- name: Execute test functions
      #  run: go test
        
      - name: Install tools
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          go install honnef.co/go/tools/cmd/staticcheck
          go get github.com/gordonklaus/ineffassign 
          go install github.com/gordonklaus/ineffassign 
          go get golang.org/x/lint/golint
          go install golang.org/x/lint/golint
          
      - name: Staticcheck
        run: staticcheck ./...    
    
      #- name: Running Staticcheck 
        #uses: dominikh/staticcheck-action@v1
        #with:
          #version: "latest"
      
      # github.com/gordonklaus/ineffassign
      - name: ineffassign
        run: ineffassign .

      - name: Running Golint   
        #uses: Jerome1337/golint-action@v1.0.2
        #with:
        #  golint-path: '.'
        run: golint -set_exit_status ./...
          
      - name: Running Gofmt 
        #uses: Jerome1337/gofmt-action@v1.0.5
        #with:
        #  gofmt-path: '.'
        #  gofmt-flags: '-e -s -w *.go'
        run: gofmt -e -s -w *.go
